name: docker-build

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: go-api-sample-${{ steps.short-sha.outputs.sha }}
    steps:
      - name: Parse short sha
        uses: benjlevesque/short-sha@v1.1
        id: short-sha

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACTIONS_ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACTIONS_ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to SharedServices Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
        #      - name: Delete existing image
        #        run: |
        #          aws ecr batch-delete-image --repository-name mytutor/circleci/ecs-deploy --image-ids imageTag=latest
        
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 776131206689.dkr.ecr.us-east-1.amazonaws.com #${{ secrets.ECR_REGISTRY }} #${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tutor-onboarding-app-be #${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: $(GITHUB_SHA:7)
        run: |
          echo "::set-output IMAGE_TAG=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
          echo $IMAGE_TAG
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          
  push-image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [prepare, docker_build]
    env:
      IMAGE_TAG: ${{ needs.prepare.outputs.IMAGE_TAG }}
    run: |
      docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
