name: docker-build

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  docker_build:
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: 776131206689.dkr.ecr.us-east-1.amazonaws.com #${{ secrets.ECR_REGISTRY }} #${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: tutor-onboarding-app-be #${{ secrets.ECR_REPOSITORY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACTIONS_ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACTIONS_ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to SharedServices Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Delete existing image
        run: |
          aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids imageTag=latest

      - name: Build, tag, and push image to Amazon ECR
        #env:
          #IMAGE_TAG: $(GITHUB_SHA:7)
        run: |
          docker build -t $GITHUB_SHA .
          docker tag $GITHUB_SHA $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

